; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -O2 -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 \
; RUN:   -verify-machineinstrs -stop-after=amdgpu-isel < %s | FileCheck %s \
; RUN:   --check-prefix=COMBINE --implicit-check-not=REG_SEQUENCE
; RUN: llc -O2 -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 \
; RUN:   -verify-machineinstrs -combiner-disabled -stop-after=amdgpu-isel < %s \
; RUN:   | FileCheck %s --check-prefix=NOCOMBINE

declare <4 x i32> @llvm.vector.extract.v4i32.v8i32(<8 x i32>, i64 immarg)

define <4 x i32> @extract_concat_multi_operand(<2 x i32> %a, <2 x i32> %b, <2 x i32> %c, <2 x i32> %d) nounwind {
  ; COMBINE-LABEL: name: extract_concat_multi_operand
  ; COMBINE: bb.0 (%ir-block.0):
  ; COMBINE-NEXT:   liveins: $vgpr4, $vgpr5, $vgpr6, $vgpr7
  ; COMBINE-NEXT: {{  $}}
  ; COMBINE-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr7
  ; COMBINE-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr6
  ; COMBINE-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr5
  ; COMBINE-NEXT:   [[COPY3:%[0-9]+]]:vgpr_32 = COPY $vgpr4
  ; COMBINE-NEXT:   $vgpr0 = COPY [[COPY3]]
  ; COMBINE-NEXT:   $vgpr1 = COPY [[COPY2]]
  ; COMBINE-NEXT:   $vgpr2 = COPY [[COPY1]]
  ; COMBINE-NEXT:   $vgpr3 = COPY [[COPY]]
  ; COMBINE-NEXT:   SI_RETURN implicit $vgpr0, implicit $vgpr1, implicit $vgpr2, implicit $vgpr3
  ;
  ; NOCOMBINE-LABEL: name: extract_concat_multi_operand
  ; NOCOMBINE: bb.0 (%ir-block.0):
  ; NOCOMBINE-NEXT:   liveins: $vgpr4, $vgpr5, $vgpr6, $vgpr7
  ; NOCOMBINE-NEXT: {{  $}}
  ; NOCOMBINE-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr7
  ; NOCOMBINE-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr6
  ; NOCOMBINE-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr5
  ; NOCOMBINE-NEXT:   [[COPY3:%[0-9]+]]:vgpr_32 = COPY $vgpr4
  ; NOCOMBINE-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:vreg_128_align2 = REG_SEQUENCE [[COPY3]], %subreg.sub0, [[COPY2]], %subreg.sub1, [[COPY1]], %subreg.sub2, [[COPY]], %subreg.sub3
  ; NOCOMBINE-NEXT:   [[COPY4:%[0-9]+]]:av_32 = COPY [[REG_SEQUENCE]].sub0
  ; NOCOMBINE-NEXT:   [[COPY5:%[0-9]+]]:av_32 = COPY [[REG_SEQUENCE]].sub1
  ; NOCOMBINE-NEXT:   [[COPY6:%[0-9]+]]:av_32 = COPY [[REG_SEQUENCE]].sub2
  ; NOCOMBINE-NEXT:   [[COPY7:%[0-9]+]]:av_32 = COPY [[REG_SEQUENCE]].sub3
  ; NOCOMBINE-NEXT:   $vgpr0 = COPY [[COPY4]]
  ; NOCOMBINE-NEXT:   $vgpr1 = COPY [[COPY5]]
  ; NOCOMBINE-NEXT:   $vgpr2 = COPY [[COPY6]]
  ; NOCOMBINE-NEXT:   $vgpr3 = COPY [[COPY7]]
  ; NOCOMBINE-NEXT:   SI_RETURN implicit $vgpr0, implicit $vgpr1, implicit $vgpr2, implicit $vgpr3
  %lo = shufflevector <2 x i32> %a, <2 x i32> %b, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %hi = shufflevector <2 x i32> %c, <2 x i32> %d, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %wide = shufflevector <4 x i32> %lo, <4 x i32> %hi, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %ext = call <4 x i32> @llvm.vector.extract.v4i32.v8i32(<8 x i32> %wide, i64 4)
  ret <4 x i32> %ext
}
